window.REALMS_DATA = {
  "version": "0.9-signature-systems-alpha",
  "status": "Signature-card systems alpha; major faction-system rewrite; not balance-locked; human playtest required",
  "global": {
    "deck_size": 30,
    "resource_split": {
      "+1": 15,
      "+2": 15
    },
    "legendary_per_faction": 1,
    "preserved_core": [
      "5-card recurring selective hand cycle",
      "20 player Health",
      "simultaneous creature-vs-creature combat",
      "alternating combat activations",
      "Realm rules unchanged from v0.7 unless separately revised"
    ],
    "notes": [
      "Permanent +HP means maximum and current HP unless text explicitly says maximum HP without restoring.",
      "Temporary/static +HP that ends can cause lethal marked damage when maximum HP falls.",
      "Signature card types: Living Geodes use Prisms, Continuum uses FLUX, Moondemons use Sigils, Harvest uses Growths, Eliteborn uses Equips.",
      "Economy remains the existing five-card round-resource system for this alpha; signature-system balance is being tested before any economy rewrite."
    ]
  },
  "factions": {
    "Living Geodes": {
      "code": "GEO",
      "realm": "Crystal Isle",
      "identity": "Dormant living crystals transform by completing color recipes with attached Prisms. Every Prism offers two colors; choose one mode when it is attached. Cracked Geodes keep their fused Prisms and their active Prism effects.",
      "universal": "PRISMATIC CRACK — Prism cards cost 3, show exactly two colors, and attach to a friendly Geode. Choose one printed color when attached; only that color's effect is active. A Geode may hold up to 4 Prisms. If the chosen Prism colors satisfy its Crack Recipe, it transforms to its Cracked form immediately. Attached Prisms remain fused and active after Crack. Cracked Geodes do not Fold.",
      "passives": {
        "Kimberlite": "KIMBERLITE — Whenever one of your Dormant Geodes Cracks, your next Prism this round costs 1 less, minimum 1. If that discounted Prism Cracks another Geode, Kimberlite refreshes.",
        "Fracture": "FRACTURE — The first Prism you attach each round contributes BOTH of its printed colors toward that Geode's Crack Recipe until that Crack check finishes. Only the color you chose provides a Prism effect."
      }
    },
    "Harvest": {
      "code": "HAR",
      "realm": "Deadlands",
      "identity": "Living biomass must keep growing. Harvest creatures still manage Nourished/Wither while attached Growth cards lie dormant, then Bloom into multi-turn biological effects when their prerequisites are fulfilled.",
      "universal": "LIFEBLOOD + GROWTH — A Harvest creature is Nourished for the round if it gains STR or maximum HP from a friendly effect; creatures entering play are Nourished that round. At end of your round, each friendly Harvest creature not Nourished takes 1 Wither damage. Growth cards cost 3 and attach dormant to a friendly Harvest creature. A creature may hold only 1 Growth. When its prerequisite is fulfilled, it Blooms and its listed ongoing effect begins.",
      "passives": {
        "Regurgitate": "REGURGITATE - Whenever one of your creatures dies, choose another friendly creature. It permanently gains +1 STR / +1 maximum and current HP.",
        "Consume": "CONSUME — Once per round during Placement, you may destroy one friendly creature. Choose another friendly creature. Distribute a number of permanent stat points equal to the destroyed creature's printed Cost + 2 between STR and maximum/current HP on the chosen creature in any combination."
      }
    },
    "Continuum": {
      "code": "CON",
      "realm": "The Endless",
      "identity": "Time is a persistent 0–5 Sequence. Continuum arms zero-cost FLUX cards and engineers exact Sequence patterns inside one round to trigger them.",
      "universal": "SEQUENCE + FLUX — Sequence is visible from 0–5 and normally Shifts at the start of your round. FLUX cards cost 0 and enter the Flux Zone armed. You may have up to 2 armed FLUX cards. Each FLUX lists an ordered Sequence pattern; if that pattern occurs during the same round, activate it immediately and discard it. Creature combat never changes Sequence unless a card says so. Reaching 5 triggers Sequence Complete at most once per round.",
      "passives": {
        "Skip Ahead": "SKIP AHEAD — Sequence moves forward 0 → 1 → 2 → 3 → 4 → 5 → 0. Once per round during Placement, discard a card to Shift forward 1 additional step.",
        "Loop Back": "LOOP BACK — Sequence begins moving forward. At 5 it Completes and reverses: 5 → 4 → 3 → 2 → 1 → 0, then reverses forward again. Effects that say Shift follow the current direction unless stated otherwise."
      }
    },
    "Moondemons": {
      "code": "MON",
      "realm": "Blood Moon",
      "identity": "Wounded predators weaponize Bloodied states and hide face-down Sigils on allies. Opponents know a Sigil is there, but not which prerequisite will spring it.",
      "universal": "BLOODIED + SIGILS — A Moondemon below maximum HP is Bloodied. Whenever it deals damage to another target, restore 2 HP to it after that damage. Sigils cost 3, attach face-down to a friendly Moondemon, and reveal when their printed prerequisite occurs. A creature may hold only 1 Sigil. Unless stated otherwise, an activated Sigil resolves once and is discarded.",
      "passives": {
        "Bloodthirst": "BLOODTHIRST - At the end of your round, each Bloodied friendly Moondemon loses 1 current HP. If a Moondemon is destroyed by this Bloodthirst loss, every other friendly Moondemon permanently gains +2 STR / +2 maximum and current HP.",
        "Frenzied": "FRENZIED - Whenever a Bloodied friendly Moondemon deals damage to another target, it permanently gains +2 STR / +2 maximum and current HP before its universal 2-HP restore. Once a Moondemon has become Bloodied, if it ever returns to full HP, destroy it immediately."
      }
    },
    "Eliteborn": {
      "code": "ELI",
      "realm": "Upper Strata",
      "identity": "Creatures and their equipment are connected into explicit Formations. Exact Formation size turns card abilities on and determines how the chosen Major rewards commitment.",
      "universal": "FORMATION - When an Eliteborn Creature enters play, choose whether it begins a new Formation or joins an existing one. Formation size counts Creatures plus attached Equips. Formation (N) means the printed effect is active while that card's Formation is exactly size N; Formation (N+) means N or greater. Equips attach to a Creature, occupy no creature slot, and add 1 to that Creature's Formation size. Each Creature may have only 1 Equip. Equips do not have STR/HP and do not receive creature damage.",
      "passives": {
        "We Stand Together": "WE STAND TOGETHER - You have 7 creature slots instead of 6. Whenever one of your Formations reaches size 5 or greater, it has Disperse. When a creature in that Formation would take damage, split that damage as evenly as possible among all creatures in that Formation; the originally targeted creature receives any remainder.",
        "Rise as One. Die as One.": "RISE AS ONE. DIE AS ONE. — Once a Creature joins a Formation, it remains bound to that Formation while in play. Whenever a card joins one of your Formations and makes its size 2 or greater, every creature currently in that Formation permanently gains +1 STR / +1 maximum and current HP. If any creature in one of your Formations dies, destroy every other creature in that Formation. Attached Equips leave when their creatures leave."
      }
    }
  },
  "cards": {
    "Living Geodes": [
      {
        "id": "GEO-001",
        "name": "Pebbleheart Hatchling",
        "type": "Creature",
        "cost": 2,
        "resource": 2,
        "statsText": "Dormant 1/4 — Crack Red+Blue → Cracked 4/4",
        "rules": "Crack — Deal 2 damage to an enemy creature.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 1,
        "hp": 4,
        "crackedStr": 4,
        "crackedHp": 4,
        "legendary": false,
        "crackRecipe": [
          "Red",
          "Blue"
        ]
      },
      {
        "id": "GEO-002",
        "name": "Quartz Bulwark",
        "type": "Creature",
        "cost": 3,
        "resource": 2,
        "statsText": "Dormant 1/6 — Crack Blue+Blue → Cracked 3/8",
        "rules": "Cracked — Taunt.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 1,
        "hp": 6,
        "crackedStr": 3,
        "crackedHp": 8,
        "legendary": false,
        "crackRecipe": [
          "Blue",
          "Blue"
        ]
      },
      {
        "id": "GEO-003",
        "name": "Lava Geode",
        "type": "Creature",
        "cost": 3,
        "resource": 1,
        "statsText": "Dormant 2/5 — Crack Red+Red → Cracked 5/5",
        "rules": "Cracked — The first time Lava Geode attacks each round, deal 1 additional damage to its target after combat.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 2,
        "hp": 5,
        "crackedStr": 5,
        "crackedHp": 5,
        "legendary": false,
        "crackRecipe": [
          "Red",
          "Red"
        ]
      },
      {
        "id": "GEO-004",
        "name": "Lumen Nodule",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "Dormant 1/5 — Crack Green+Blue → Cracked 3/7",
        "rules": "Crack — Restore 3 HP divided among friendly creatures.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 1,
        "hp": 5,
        "crackedStr": 3,
        "crackedHp": 7,
        "legendary": false,
        "crackRecipe": [
          "Green",
          "Blue"
        ]
      },
      {
        "id": "GEO-005",
        "name": "Razor Geode",
        "type": "Creature",
        "cost": 4,
        "resource": 1,
        "statsText": "Dormant 3/4 — Crack Red+Violet → Cracked 6/4",
        "rules": "Cracked — The first time Razor Geode attacks each round, it gains +2 STR for that combat.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 3,
        "hp": 4,
        "crackedStr": 6,
        "crackedHp": 4,
        "legendary": false,
        "crackRecipe": [
          "Red",
          "Violet"
        ]
      },
      {
        "id": "GEO-006",
        "name": "Mirrorstone Egg",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "Dormant 1/5 — Crack Blue+Violet → Cracked 4/6",
        "rules": "Crack — Choose an enemy creature. Mirrorstone Egg gains STR equal to that creature's printed STR this round, maximum +4 STR.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 1,
        "hp": 5,
        "crackedStr": 4,
        "crackedHp": 6,
        "legendary": false,
        "crackRecipe": [
          "Blue",
          "Violet"
        ]
      },
      {
        "id": "GEO-007",
        "name": "Deepcore Cocoon",
        "type": "Creature",
        "cost": 5,
        "resource": 1,
        "statsText": "Dormant 2/7 — Crack Blue+Green+Green → Cracked 6/8",
        "rules": "Dormant — Taunt. Crack — Restore 2 HP to Deepcore Cocoon.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 2,
        "hp": 7,
        "crackedStr": 6,
        "crackedHp": 8,
        "legendary": false,
        "crackRecipe": [
          "Blue",
          "Green",
          "Green"
        ]
      },
      {
        "id": "GEO-008",
        "name": "Gemscale Larva",
        "type": "Creature",
        "cost": 5,
        "resource": 2,
        "statsText": "Dormant 2/5 — Crack Red+Green → Cracked 6/5",
        "rules": "Crack — If Gemscale Larva has not acted this round, it immediately gains one additional combat action.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 2,
        "hp": 5,
        "crackedStr": 6,
        "crackedHp": 5,
        "legendary": false,
        "crackRecipe": [
          "Red",
          "Green"
        ]
      },
      {
        "id": "GEO-009",
        "name": "Stressborn Cluster",
        "type": "Creature",
        "cost": 5,
        "resource": 1,
        "statsText": "Dormant 0/8 — Crack Red+Violet → Cracked 7/6",
        "rules": "The first time each round a Prism is attached to Stressborn Cluster, it gains +2 STR this round. Crack — Draw 1 card.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 0,
        "hp": 8,
        "crackedStr": 7,
        "crackedHp": 6,
        "legendary": false,
        "crackRecipe": [
          "Red",
          "Violet"
        ]
      },
      {
        "id": "GEO-010",
        "name": "Shard Choir Seed",
        "type": "Creature",
        "cost": 5,
        "resource": 2,
        "statsText": "Dormant 1/6 — Crack Green+Violet → Cracked 4/6",
        "rules": "Cracked — The first three times each round another friendly Geode receives a Prism, Shard Choir Seed gains +1 STR this round.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 1,
        "hp": 6,
        "crackedStr": 4,
        "crackedHp": 6,
        "legendary": false,
        "crackRecipe": [
          "Green",
          "Violet"
        ]
      },
      {
        "id": "GEO-011",
        "name": "Crown Geode",
        "type": "Creature",
        "cost": 6,
        "resource": 1,
        "statsText": "Dormant 2/7 — Crack Blue+Violet+Violet → Cracked 6/9",
        "rules": "Crack — Draw 2 cards, then put 1 card from your hand on the bottom of your deck.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 2,
        "hp": 7,
        "crackedStr": 6,
        "crackedHp": 9,
        "legendary": false,
        "crackRecipe": [
          "Blue",
          "Violet",
          "Violet"
        ]
      },
      {
        "id": "GEO-012",
        "name": "Worldheart Geode",
        "type": "Creature",
        "cost": 8,
        "resource": 1,
        "statsText": "Dormant 3/9 — Crack Green+Green+Blue → Cracked 8/10",
        "rules": "At the end of your round, if Worldheart Geode has at least 2 Prisms attached, restore 2 HP to another friendly Geode.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 3,
        "hp": 9,
        "crackedStr": 8,
        "crackedHp": 10,
        "legendary": false,
        "crackRecipe": [
          "Green",
          "Green",
          "Blue"
        ]
      },
      {
        "id": "GEO-013",
        "name": "Violet Shard",
        "type": "Prism",
        "cost": 3,
        "resource": 2,
        "statsText": "Red / Blue",
        "rules": "PRISM — Choose Red or Blue when attached. Red: Attached Geode gains +2 STR during its first combat action each round. Blue: Whenever attached Geode is about to take combat damage, it gains Shield 1 before that damage.",
        "faction": "Living Geodes",
        "code": "GEO",
        "colors": [
          "Red",
          "Blue"
        ],
        "prismText": {
          "Red": "Attached Geode gains +2 STR during its first combat action each round.",
          "Blue": "Whenever attached Geode is about to take combat damage, it gains Shield 1 before that damage."
        },
        "prismModes": {
          "Red": {
            "kind": "firstCombatStr",
            "amount": 2
          },
          "Blue": {
            "kind": "combatShield",
            "amount": 1
          }
        }
      },
      {
        "id": "GEO-014",
        "name": "Emberbloom Prism",
        "type": "Prism",
        "cost": 3,
        "resource": 2,
        "statsText": "Red / Green",
        "rules": "PRISM — Choose Red or Green when attached. Red: Attached Geode has +1 STR. Green: At the start of your round, restore 1 HP to attached Geode.",
        "faction": "Living Geodes",
        "code": "GEO",
        "colors": [
          "Red",
          "Green"
        ],
        "prismText": {
          "Red": "Attached Geode has +1 STR.",
          "Green": "At the start of your round, restore 1 HP to attached Geode."
        },
        "prismModes": {
          "Red": {
            "kind": "staticStr",
            "amount": 1
          },
          "Green": {
            "kind": "startHeal",
            "amount": 1
          }
        }
      },
      {
        "id": "GEO-015",
        "name": "Riftglass Prism",
        "type": "Prism",
        "cost": 3,
        "resource": 1,
        "statsText": "Red / Violet",
        "rules": "PRISM — Choose Red or Violet when attached. Red: Attached Geode deals +2 damage on direct attacks. Violet: The first time each round you attach another Prism, attached Geode gains +1 STR / +1 maximum and current HP this round.",
        "faction": "Living Geodes",
        "code": "GEO",
        "colors": [
          "Red",
          "Violet"
        ],
        "prismText": {
          "Red": "Attached Geode deals +2 damage on direct attacks.",
          "Violet": "The first time each round you attach another Prism, attached Geode gains +1 STR / +1 maximum and current HP this round."
        },
        "prismModes": {
          "Red": {
            "kind": "directDamage",
            "amount": 2
          },
          "Violet": {
            "kind": "onPrismTempStats",
            "str": 1,
            "hp": 1
          }
        }
      },
      {
        "id": "GEO-016",
        "name": "Tidemoss Prism",
        "type": "Prism",
        "cost": 3,
        "resource": 2,
        "statsText": "Blue / Green",
        "rules": "PRISM — Choose Blue or Green when attached. Blue: The first damage attached Geode takes each round is reduced by 1. Green: At the end of your round, restore 2 HP to attached Geode.",
        "faction": "Living Geodes",
        "code": "GEO",
        "colors": [
          "Blue",
          "Green"
        ],
        "prismText": {
          "Blue": "The first damage attached Geode takes each round is reduced by 1.",
          "Green": "At the end of your round, restore 2 HP to attached Geode."
        },
        "prismModes": {
          "Blue": {
            "kind": "firstDamageReduce",
            "amount": 1
          },
          "Green": {
            "kind": "endHeal",
            "amount": 2
          }
        }
      },
      {
        "id": "GEO-017",
        "name": "Mirror Prism",
        "type": "Prism",
        "cost": 3,
        "resource": 2,
        "statsText": "Blue / Violet",
        "rules": "PRISM — Choose Blue or Violet when attached. Blue: At the start of Action Phase, attached Geode gains Shield 1. Violet: For Crack Recipe checks, this Prism may satisfy any one missing color instead of Violet.",
        "faction": "Living Geodes",
        "code": "GEO",
        "colors": [
          "Blue",
          "Violet"
        ],
        "prismText": {
          "Blue": "At the start of Action Phase, attached Geode gains Shield 1.",
          "Violet": "For Crack Recipe checks, this Prism may satisfy any one missing color instead of Violet."
        },
        "prismModes": {
          "Blue": {
            "kind": "actionShield",
            "amount": 1
          },
          "Violet": {
            "kind": "wildRecipe",
            "amount": 1
          }
        }
      },
      {
        "id": "GEO-018",
        "name": "Verdant Echo Prism",
        "type": "Prism",
        "cost": 3,
        "resource": 1,
        "statsText": "Green / Violet",
        "rules": "PRISM — Choose Green or Violet when attached. Green: When attached Geode Cracks, restore 4 HP to it. Violet: When attached Geode Cracks, draw 1 card, then put 1 card from your hand on the bottom of your deck.",
        "faction": "Living Geodes",
        "code": "GEO",
        "colors": [
          "Green",
          "Violet"
        ],
        "prismText": {
          "Green": "When attached Geode Cracks, restore 4 HP to it.",
          "Violet": "When attached Geode Cracks, draw 1 card, then put 1 card from your hand on the bottom of your deck."
        },
        "prismModes": {
          "Green": {
            "kind": "crackHeal",
            "amount": 4
          },
          "Violet": {
            "kind": "crackCycle",
            "amount": 1
          }
        }
      },
      {
        "id": "GEO-019",
        "name": "Refraction Screen",
        "type": "Trap",
        "cost": 3,
        "resource": 1,
        "statsText": "-",
        "rules": "When a friendly Dormant Geode with at least 1 Prism is attacked, it gains Shield 2 before combat.",
        "faction": "Living Geodes",
        "code": "GEO"
      },
      {
        "id": "GEO-020",
        "name": "Emergency Facet",
        "type": "Trap",
        "cost": 5,
        "resource": 1,
        "statsText": "-",
        "rules": "When a friendly Dormant Geode would be destroyed by damage, if it is exactly one color short of its Crack Recipe, treat one attached Prism as a wild color for that Crack check. If it Cracks, prevent 3 of that damage.",
        "faction": "Living Geodes",
        "code": "GEO"
      },
      {
        "id": "GEO-021",
        "name": "Seed of the Deep",
        "type": "Creature",
        "cost": 2,
        "resource": 2,
        "statsText": "Dormant 0/5 — Crack Green+Green → Cracked 3/7",
        "rules": "The first time each round a Prism is attached to Seed of the Deep, restore 1 HP to it. Cracked — At the start of your round, restore 1 additional HP to it.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 0,
        "hp": 5,
        "crackedStr": 3,
        "crackedHp": 7,
        "legendary": false,
        "crackRecipe": [
          "Green",
          "Green"
        ]
      },
      {
        "id": "GEO-022",
        "name": "Faultborn Sentinel",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "Dormant 2/6 — Crack Blue+Red → Cracked 5/7",
        "rules": "When Faultborn Sentinel enters play, you may move one Prism from another friendly Dormant Geode onto it, keeping that Prism's chosen color. Cracked — The first damage it takes each round is reduced by 1.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 2,
        "hp": 6,
        "crackedStr": 5,
        "crackedHp": 7,
        "legendary": false,
        "crackRecipe": [
          "Blue",
          "Red"
        ]
      },
      {
        "id": "GEO-023",
        "name": "Crystal Parasite",
        "type": "Creature",
        "cost": 3,
        "resource": 1,
        "statsText": "Dormant 1/4 — Crack Violet+Violet → Cracked 4/5",
        "rules": "The first time each round another friendly Geode receives a Prism, Crystal Parasite gains +1 STR this round and restores 1 HP.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 1,
        "hp": 4,
        "crackedStr": 4,
        "crackedHp": 5,
        "legendary": false,
        "crackRecipe": [
          "Violet",
          "Violet"
        ]
      },
      {
        "id": "GEO-024",
        "name": "Glassjaw Colossus",
        "type": "Creature",
        "cost": 6,
        "resource": 1,
        "statsText": "Dormant 5/5 — Crack Red+Blue → Cracked 9/6",
        "rules": "Whenever Glassjaw Colossus takes 3 or more damage from one source and survives, it gains +2 STR this round.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 5,
        "hp": 5,
        "crackedStr": 9,
        "crackedHp": 6,
        "legendary": false,
        "crackRecipe": [
          "Red",
          "Blue"
        ]
      },
      {
        "id": "GEO-025",
        "name": "Prismatic Broodmother",
        "type": "Creature",
        "cost": 7,
        "resource": 1,
        "statsText": "Dormant 3/8 — Crack Green+Violet+Red → Cracked 6/9",
        "rules": "Crack — Summon a 0/3 Shardling. A Shardling Cracks into 3/3 when any Prism is attached to it.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 3,
        "hp": 8,
        "crackedStr": 6,
        "crackedHp": 9,
        "legendary": false,
        "crackRecipe": [
          "Green",
          "Violet",
          "Red"
        ]
      },
      {
        "id": "GEO-026",
        "name": "Aurex, Worldheart Unsealed",
        "type": "Legendary Creature",
        "cost": 9,
        "resource": 2,
        "statsText": "Dormant 4/11 — Crack Red+Blue+Green+Violet → Cracked 10/11",
        "rules": "Whenever another friendly Geode Cracks, restore 1 HP to Aurex. KIMBERLITE — Mantle Detonation: the first Kimberlite discount each round is 2 instead of 1. FRACTURE — Fault Network: the first Fracture Prism each round also lets you draw 1 card, then put 1 card from your hand on the bottom of your deck.",
        "faction": "Living Geodes",
        "code": "GEO",
        "str": 4,
        "hp": 11,
        "crackedStr": 10,
        "crackedHp": 11,
        "legendary": true,
        "crackRecipe": [
          "Red",
          "Blue",
          "Green",
          "Violet"
        ]
      },
      {
        "id": "GEO-027",
        "name": "Prismatic Search",
        "type": "Spell",
        "cost": 3,
        "resource": 2,
        "statsText": "-",
        "rules": "Look at the top 4 cards of your deck. Put a Prism among them into your hand; put the rest on the bottom in any order.",
        "faction": "Living Geodes",
        "code": "GEO"
      },
      {
        "id": "GEO-028",
        "name": "Refract",
        "type": "Spell",
        "cost": 4,
        "resource": 2,
        "statsText": "-",
        "rules": "Choose a Prism attached to a friendly Dormant Geode. Switch it to its other printed color. Re-check that Geode's Crack Recipe.",
        "faction": "Living Geodes",
        "code": "GEO"
      },
      {
        "id": "GEO-029",
        "name": "Crystal Relay",
        "type": "Spell",
        "cost": 5,
        "resource": 1,
        "statsText": "-",
        "rules": "Move one Prism from a friendly Geode to another friendly Dormant Geode, keeping its chosen color. Then restore 2 HP to both Geodes.",
        "faction": "Living Geodes",
        "code": "GEO"
      },
      {
        "id": "GEO-030",
        "name": "Perfect Alignment",
        "type": "Trap",
        "cost": 4,
        "resource": 1,
        "statsText": "-",
        "rules": "When you attach a Prism that leaves a Dormant Geode exactly one color short of Cracking, draw 1 card. The next Prism you play this round costs 1 less, minimum 1.",
        "faction": "Living Geodes",
        "code": "GEO"
      }
    ],
    "Harvest": [
      {
        "id": "HAR-001",
        "name": "Furrow Keeper",
        "type": "Creature",
        "cost": 3,
        "resource": 2,
        "statsText": "1/4",
        "rules": "At the end of your round before Wither, another friendly Harvest creature gains +1 maximum and current HP permanently.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 1,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "HAR-002",
        "name": "Briarback",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "3/5",
        "rules": "The first time each round Briarback survives creature combat damage, it gains +1 maximum and current HP permanently.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 3,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "HAR-003",
        "name": "Hollow Grazer",
        "type": "Creature",
        "cost": 4,
        "resource": 1,
        "statsText": "3/5",
        "rules": "Before attacking, you may reduce Hollow Grazer's maximum and current HP by 2 permanently, minimum 1. If you do, it gains +3 STR this round.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 3,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "HAR-004",
        "name": "Graftkeeper",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "2/5",
        "rules": "On play, move up to 2 permanent STR or maximum-HP bonus points from your other friendly creatures onto Graftkeeper in any combination.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 2,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "HAR-005",
        "name": "Blightmouth",
        "type": "Creature",
        "cost": 4,
        "resource": 1,
        "statsText": "3/4",
        "rules": "The first time each round Blightmouth gains STR or maximum HP, its next damage dealt this round is increased by 2.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 3,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "HAR-006",
        "name": "The Walking Orchard",
        "type": "Creature",
        "cost": 7,
        "resource": 1,
        "statsText": "3/8",
        "rules": "At the start of your round, choose up to two other friendly Harvest creatures. Each gains +1 maximum and current HP permanently.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 3,
        "hp": 8,
        "legendary": false
      },
      {
        "id": "HAR-007",
        "name": "Prune the Weak",
        "type": "Spell",
        "cost": 3,
        "resource": 1,
        "statsText": "-",
        "rules": "Destroy a friendly creature. Another friendly creature gains STR equal to the destroyed creature's current STR, maximum +3 STR, permanently.",
        "faction": "Harvest",
        "code": "HAR"
      },
      {
        "id": "HAR-008",
        "name": "Forced Bloom",
        "type": "Spell",
        "cost": 2,
        "resource": 2,
        "statsText": "-",
        "rules": "A friendly creature gains +3 STR this round. After it takes a combat action this round, deal 1 damage to it.",
        "faction": "Harvest",
        "code": "HAR"
      },
      {
        "id": "HAR-009",
        "name": "Overgrowth",
        "type": "Spell",
        "cost": 3,
        "resource": 1,
        "statsText": "-",
        "rules": "A friendly creature gains +4 maximum and current HP permanently. It cannot take a combat action this round.",
        "faction": "Harvest",
        "code": "HAR"
      },
      {
        "id": "HAR-010",
        "name": "Thorn Tithe",
        "type": "Trap",
        "cost": 3,
        "resource": 2,
        "statsText": "-",
        "rules": "After a friendly Harvest creature survives combat damage, it gains +1 STR / +1 maximum and current HP permanently.",
        "faction": "Harvest",
        "code": "HAR"
      },
      {
        "id": "HAR-011",
        "name": "Rootbound Tender",
        "type": "Creature",
        "cost": 2,
        "resource": 1,
        "statsText": "1/3",
        "rules": "Once per round, when another friendly Harvest creature would take Wither damage, it gains +1 maximum and current HP permanently instead.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 1,
        "hp": 3,
        "legendary": false
      },
      {
        "id": "HAR-012",
        "name": "Splitbark",
        "type": "Creature",
        "cost": 3,
        "resource": 2,
        "statsText": "2/4",
        "rules": "The first time each round Splitbark gains permanent STR or maximum HP, another friendly creature gains +1 of the same stat permanently.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 2,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "HAR-013",
        "name": "Rejuvenation",
        "type": "Growth",
        "cost": 3,
        "resource": 1,
        "statsText": "Dormant ally attachment",
        "rules": "GROWTH — Attach dormant to a friendly Harvest creature. When attached ally would take fatal damage, Bloom: leave it at 1 HP instead. For its controller's next 2 turns, restore 2 HP to it at the start and end of the turn.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 3,
        "hp": 4,
        "legendary": false,
        "growthEffect": "rejuvenation"
      },
      {
        "id": "HAR-014",
        "name": "Thornbloom",
        "type": "Growth",
        "cost": 3,
        "resource": 2,
        "statsText": "Dormant ally attachment",
        "rules": "GROWTH — Attach dormant to a friendly Harvest creature. When attached ally survives creature combat damage, Bloom for 2 turns. At the start of each of those turns it gains +2 STR that round.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 2,
        "hp": 6,
        "legendary": false,
        "growthEffect": "thornbloom"
      },
      {
        "id": "HAR-015",
        "name": "Carrion Root",
        "type": "Growth",
        "cost": 3,
        "resource": 1,
        "statsText": "Dormant ally attachment",
        "rules": "GROWTH — Attach dormant to a friendly Harvest creature. When another friendly creature dies, Bloom for 2 turns. At the start and end of each of those turns, attached ally permanently gains +1 STR / +1 maximum and current HP.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 3,
        "hp": 7,
        "legendary": false,
        "growthEffect": "carrion"
      },
      {
        "id": "HAR-016",
        "name": "Nourishing Mycelium",
        "type": "Growth",
        "cost": 3,
        "resource": 1,
        "statsText": "Dormant ally attachment",
        "rules": "GROWTH — Attach dormant to a friendly Harvest creature. When attached ally becomes Nourished after being unnourished, Bloom for 2 turns. While Blooming it cannot take Wither damage; restore 1 HP to it at the start and end of each turn.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 5,
        "hp": 10,
        "legendary": false,
        "growthEffect": "mycelium"
      },
      {
        "id": "HAR-017",
        "name": "Predator Vine",
        "type": "Growth",
        "cost": 3,
        "resource": 2,
        "statsText": "Dormant ally attachment",
        "rules": "GROWTH — Attach dormant to a friendly Harvest creature. When attached ally destroys an enemy creature in combat, Bloom for 2 turns. The first time each turn it deals damage to another target, it permanently gains +1 STR / +1 maximum and current HP.",
        "faction": "Harvest",
        "code": "HAR",
        "growthEffect": "predator"
      },
      {
        "id": "HAR-018",
        "name": "Ironbark Bloom",
        "type": "Growth",
        "cost": 3,
        "resource": 2,
        "statsText": "Dormant ally attachment",
        "rules": "GROWTH — Attach dormant to a friendly Harvest creature. When attached ally takes 3 or more damage from one source and survives, Bloom for 2 turns. At the start and end of each turn, give it Shield 2.",
        "faction": "Harvest",
        "code": "HAR",
        "growthEffect": "ironbark"
      },
      {
        "id": "HAR-019",
        "name": "Cultivate",
        "type": "Spell",
        "cost": 5,
        "resource": 1,
        "statsText": "-",
        "rules": "Choose two different friendly creatures. Each gains +1 STR / +1 maximum and current HP permanently.",
        "faction": "Harvest",
        "code": "HAR"
      },
      {
        "id": "HAR-020",
        "name": "Ripen Under Pressure",
        "type": "Trap",
        "cost": 3,
        "resource": 1,
        "statsText": "-",
        "rules": "After a friendly creature survives enemy creature damage, it gains +2 maximum and current HP permanently.",
        "faction": "Harvest",
        "code": "HAR"
      },
      {
        "id": "HAR-021",
        "name": "Sapkeeper",
        "type": "Creature",
        "cost": 2,
        "resource": 2,
        "statsText": "1/3",
        "rules": "The first time each round another friendly creature gains maximum HP, restore 1 HP to it and Sapkeeper gains +1 STR this round.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 1,
        "hp": 3,
        "legendary": false
      },
      {
        "id": "HAR-022",
        "name": "Graft Ox",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "3/5",
        "rules": "The first time each round permanent STR or maximum-HP bonuses are moved onto Graft Ox, it gains +1 STR / +1 maximum and current HP permanently.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 3,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "HAR-023",
        "name": "Thornfed Stag",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "4/4",
        "rules": "The first time each round Thornfed Stag takes damage from one of your own cards or abilities, it gains +1 STR / +1 maximum and current HP permanently.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 4,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "HAR-024",
        "name": "Orchard Midwife",
        "type": "Creature",
        "cost": 5,
        "resource": 1,
        "statsText": "2/7",
        "rules": "At the end of your round before Wither, choose a damaged friendly creature that is Nourished. Restore 2 HP to it.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 2,
        "hp": 7,
        "legendary": false
      },
      {
        "id": "HAR-025",
        "name": "Feastroot Titan",
        "type": "Creature",
        "cost": 7,
        "resource": 1,
        "statsText": "5/9",
        "rules": "Once per round, reduce Feastroot Titan's maximum and current HP by 2 permanently, minimum 1. Another friendly creature gains +2 STR / +2 maximum and current HP permanently.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 5,
        "hp": 9,
        "legendary": false
      },
      {
        "id": "HAR-026",
        "name": "Eldergrowth, the First Orchard",
        "type": "Legendary Creature",
        "cost": 9,
        "resource": 2,
        "statsText": "6/12",
        "rules": "CONSUME — Feast While Warm: for the first creature you Consume each round, treat its printed Cost as 2 higher before calculating the Consume bonus, maximum effective Cost 9. REGURGITATE — when another friendly creature dies, the first Regurgitate bonus each round may be split as +1/+1 to two different survivors instead of one.",
        "faction": "Harvest",
        "code": "HAR",
        "str": 6,
        "hp": 12,
        "legendary": true
      },
      {
        "id": "HAR-027",
        "name": "Selective Breeding",
        "type": "Spell",
        "cost": 3,
        "resource": 2,
        "statsText": "-",
        "rules": "Choose a friendly creature with a permanent STR or maximum-HP bonus. Another friendly creature gains +1 permanent bonus of one stat type that the chosen creature has gained permanently.",
        "faction": "Harvest",
        "code": "HAR"
      },
      {
        "id": "HAR-028",
        "name": "Cull and Compost",
        "type": "Spell",
        "cost": 4,
        "resource": 2,
        "statsText": "-",
        "rules": "Destroy a damaged friendly creature. Draw 2 cards. Another friendly creature gains +2 maximum and current HP permanently.",
        "faction": "Harvest",
        "code": "HAR"
      },
      {
        "id": "HAR-029",
        "name": "Late Harvest",
        "type": "Spell",
        "cost": 6,
        "resource": 1,
        "statsText": "-",
        "rules": "Remove up to 4 permanent STR or maximum-HP bonus points from one friendly creature. Distribute the same number of permanent STR or maximum-HP bonus points among your other friendly creatures in any combination.",
        "faction": "Harvest",
        "code": "HAR"
      },
      {
        "id": "HAR-030",
        "name": "Deep Roots",
        "type": "Trap",
        "cost": 4,
        "resource": 1,
        "statsText": "-",
        "rules": "When a friendly creature with permanent stat bonuses would be destroyed by damage, remove up to 2 of those bonus points. Prevent 2 damage for each point removed.",
        "faction": "Harvest",
        "code": "HAR"
      }
    ],
    "Continuum": [
      {
        "id": "CON-001",
        "name": "Firststep Scout",
        "type": "Creature",
        "cost": 1,
        "resource": 1,
        "statsText": "2/3",
        "rules": "High Sequence (4/5) - Firststep Scout has +1 STR / +1 maximum and current HP.",
        "faction": "Continuum",
        "code": "CON",
        "str": 2,
        "hp": 3,
        "legendary": false
      },
      {
        "id": "CON-002",
        "name": "Second Bell Adept",
        "type": "Creature",
        "cost": 2,
        "resource": 2,
        "statsText": "2/4",
        "rules": "High Sequence (4/5) - The first time each round your Sequence changes while remaining at 4 or 5, Second Bell Adept gains +2 STR this round.",
        "faction": "Continuum",
        "code": "CON",
        "str": 2,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "CON-003",
        "name": "Third Motion Engine",
        "type": "Creature",
        "cost": 3,
        "resource": 1,
        "statsText": "2/5",
        "rules": "Sequence Complete - Your next card this round costs 2 less, minimum 1.",
        "faction": "Continuum",
        "code": "CON",
        "str": 2,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "CON-004",
        "name": "Fourth Horizon",
        "type": "Creature",
        "cost": 5,
        "resource": 1,
        "statsText": "4/5",
        "rules": "High Sequence (4/5) - Fourth Horizon has +2 STR / +2 maximum and current HP.",
        "faction": "Continuum",
        "code": "CON",
        "str": 4,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "CON-005",
        "name": "Zero Point Witness",
        "type": "Creature",
        "cost": 2,
        "resource": 2,
        "statsText": "2/4",
        "rules": "Sequence Complete - Restore 2 Health to yourself and 2 HP to Zero Point Witness.",
        "faction": "Continuum",
        "code": "CON",
        "str": 2,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "CON-006",
        "name": "Interval Keeper",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "3/5",
        "rules": "High Sequence (4/5) - The first time each round your Sequence changes, draw 1 card, then put 1 card from your hand on the bottom of your deck.",
        "faction": "Continuum",
        "code": "CON",
        "str": 3,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "CON-007",
        "name": "Relay Walker",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "3/4",
        "rules": "Sequence Complete - Ready another friendly creature that has already acted this round. It may take one additional combat action this round.",
        "faction": "Continuum",
        "code": "CON",
        "str": 3,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "CON-008",
        "name": "Fifth Vector",
        "type": "Creature",
        "cost": 6,
        "resource": 1,
        "statsText": "5/5",
        "rules": "Sequence Complete - Fifth Vector gains +3 STR this round. If it has not acted this round, it may immediately take one combat action.",
        "faction": "Continuum",
        "code": "CON",
        "str": 5,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "CON-009",
        "name": "Between Moments",
        "type": "Creature",
        "cost": 3,
        "resource": 2,
        "statsText": "2/6",
        "rules": "High Sequence (4/5) - Between Moments has Taunt and +0 STR / +2 maximum and current HP.",
        "faction": "Continuum",
        "code": "CON",
        "str": 2,
        "hp": 6,
        "legendary": false
      },
      {
        "id": "CON-010",
        "name": "Continuum Scribe",
        "type": "Creature",
        "cost": 5,
        "resource": 1,
        "statsText": "3/6",
        "rules": "Sequence Complete - Draw 2 cards, then put 1 card from your hand on the bottom of your deck.",
        "faction": "Continuum",
        "code": "CON",
        "str": 3,
        "hp": 6,
        "legendary": false
      },
      {
        "id": "CON-011",
        "name": "Endline Predator",
        "type": "Creature",
        "cost": 6,
        "resource": 1,
        "statsText": "5/6",
        "rules": "High Sequence (4/5) - Endline Predator has +3 STR.",
        "faction": "Continuum",
        "code": "CON",
        "str": 5,
        "hp": 6,
        "legendary": false
      },
      {
        "id": "CON-012",
        "name": "Ourostep Architect",
        "type": "Creature",
        "cost": 7,
        "resource": 1,
        "statsText": "5/7",
        "rules": "On play, Shift your Sequence 1 step in its current direction. High Sequence (4/5) - Once per round when your Sequence would Shift, you may keep it at its current number instead.",
        "faction": "Continuum",
        "code": "CON",
        "str": 5,
        "hp": 7,
        "legendary": false
      },
      {
        "id": "CON-013",
        "name": "Frozen in Balance",
        "type": "FLUX",
        "cost": 0,
        "resource": 2,
        "statsText": "1 → 2 → 3",
        "rules": "FLUX 0 — If Sequence 1 → 2 → 3 occurs during one round, activate. For your next 3 turns, Sequence cannot advance above 4; effects that would advance it while at 4 do not move it.",
        "faction": "Continuum",
        "code": "CON",
        "fluxPattern": [
          1,
          2,
          3
        ],
        "fluxEffect": "freezeAt4"
      },
      {
        "id": "CON-014",
        "name": "Borrowed Future",
        "type": "FLUX",
        "cost": 0,
        "resource": 1,
        "statsText": "2 → 3 → 4",
        "rules": "FLUX 0 — If Sequence 2 → 3 → 4 occurs during one round, activate. Draw 2 cards, then put 1 card from your hand on the bottom of your deck.",
        "faction": "Continuum",
        "code": "CON",
        "fluxPattern": [
          2,
          3,
          4
        ],
        "fluxEffect": "drawCycle"
      },
      {
        "id": "CON-015",
        "name": "Split Second",
        "type": "FLUX",
        "cost": 0,
        "resource": 2,
        "statsText": "3 → 4 → 5",
        "rules": "FLUX 0 — If Sequence 3 → 4 → 5 occurs during one round, activate. All friendly creatures gain +2 STR this round.",
        "faction": "Continuum",
        "code": "CON",
        "fluxPattern": [
          3,
          4,
          5
        ],
        "fluxEffect": "battleSurge"
      },
      {
        "id": "CON-016",
        "name": "Backstep Paradox",
        "type": "FLUX",
        "cost": 0,
        "resource": 2,
        "statsText": "5 → 4 → 3",
        "rules": "FLUX 0 — If Sequence 5 → 4 → 3 occurs during one round, activate. Restore 2 HP to every friendly creature.",
        "faction": "Continuum",
        "code": "CON",
        "fluxPattern": [
          5,
          4,
          3
        ],
        "fluxEffect": "rewindMend"
      },
      {
        "id": "CON-017",
        "name": "Impossible Return",
        "type": "FLUX",
        "cost": 0,
        "resource": 1,
        "statsText": "3 → 2 → 1",
        "rules": "FLUX 0 — If Sequence 3 → 2 → 1 occurs during one round, activate. Draw 2 cards, then put 2 cards from your hand on the bottom of your deck.",
        "faction": "Continuum",
        "code": "CON",
        "fluxPattern": [
          3,
          2,
          1
        ],
        "fluxEffect": "deepCycle"
      },
      {
        "id": "CON-018",
        "name": "Möbius Lock",
        "type": "FLUX",
        "cost": 0,
        "resource": 1,
        "statsText": "4 → 5 → 4",
        "rules": "FLUX 0 — If Sequence 4 → 5 → 4 occurs during one round, activate. Your printed High Sequence effects remain active until the end of your next round even if Sequence leaves 4/5. Draw 1 card.",
        "faction": "Continuum",
        "code": "CON",
        "fluxPattern": [
          4,
          5,
          4
        ],
        "fluxEffect": "lingerHigh"
      },
      {
        "id": "CON-019",
        "name": "Out of Order",
        "type": "Trap",
        "cost": 2,
        "resource": 2,
        "statsText": "-",
        "rules": "When an enemy creature attacks, High Sequence (4/5) - That attacker gets -3 STR for this combat. If you are not at High Sequence, this Trap remains set.",
        "faction": "Continuum",
        "code": "CON"
      },
      {
        "id": "CON-020",
        "name": "Last Before First",
        "type": "Trap",
        "cost": 4,
        "resource": 1,
        "statsText": "-",
        "rules": "When a friendly creature is destroyed, Shift your Sequence 1 step in its current direction. Sequence Complete - Draw 1 card.",
        "faction": "Continuum",
        "code": "CON"
      },
      {
        "id": "CON-021",
        "name": "Opening Echo",
        "type": "Creature",
        "cost": 1,
        "resource": 2,
        "statsText": "2/2",
        "rules": "On play, Shift your Sequence 1 step in its current direction. Sequence Complete - If this play caused the completion, draw 1 card.",
        "faction": "Continuum",
        "code": "CON",
        "str": 2,
        "hp": 2,
        "legendary": false
      },
      {
        "id": "CON-022",
        "name": "Midpoint Warden",
        "type": "Creature",
        "cost": 3,
        "resource": 2,
        "statsText": "2/5",
        "rules": "High Sequence (4/5) - The first time each round a friendly creature would take damage, reduce that damage by 2.",
        "faction": "Continuum",
        "code": "CON",
        "str": 2,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "CON-023",
        "name": "Triple Threader",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "3/4",
        "rules": "Sequence Complete - Draw 2 cards, then put 1 card from your hand on the bottom of your deck.",
        "faction": "Continuum",
        "code": "CON",
        "str": 3,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "CON-024",
        "name": "Loop Hound",
        "type": "Creature",
        "cost": 5,
        "resource": 1,
        "statsText": "5/4",
        "rules": "High Sequence (4/5) - Loop Hound has +2 STR / +2 maximum and current HP. Whenever your Sequence moves from 5 to 4, ready Loop Hound.",
        "faction": "Continuum",
        "code": "CON",
        "str": 5,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "CON-025",
        "name": "Seventh Step",
        "type": "Creature",
        "cost": 6,
        "resource": 1,
        "statsText": "4/7",
        "rules": "High Sequence (4/5) - The first Spell you play each round costs 2 less, minimum 1.",
        "faction": "Continuum",
        "code": "CON",
        "str": 4,
        "hp": 7,
        "legendary": false
      },
      {
        "id": "CON-026",
        "name": "The Infinite Interval",
        "type": "Legendary Creature",
        "cost": 9,
        "resource": 2,
        "statsText": "7/9",
        "rules": "High Sequence (4/5) — The Infinite Interval has +2 STR / +2 maximum and current HP. Sequence Complete — Draw 2 cards; your next card this round costs 2 less, minimum 1. SKIP AHEAD — Perfect Acceleration: you may use Skip Ahead twice per round; each use still requires its discard. LOOP BACK — Closed Circuit: the first time each round your Sequence moves backward while at 4 or 5, all friendly creatures with a High Sequence effect gain +1 STR / +1 maximum and current HP this round.",
        "faction": "Continuum",
        "code": "CON",
        "str": 7,
        "hp": 9,
        "legendary": true
      },
      {
        "id": "CON-027",
        "name": "Count to Three",
        "type": "Spell",
        "cost": 3,
        "resource": 2,
        "statsText": "-",
        "rules": "Shift your Sequence 1 step in its current direction. High Sequence (4/5) - Your next three cards this round each cost 1 less, minimum 1.",
        "faction": "Continuum",
        "code": "CON"
      },
      {
        "id": "CON-028",
        "name": "Repeat Measure",
        "type": "Spell",
        "cost": 4,
        "resource": 2,
        "statsText": "-",
        "rules": "Sequence Complete - Copy one other Sequence Complete effect you control that triggered from this completion. You may choose new legal targets.",
        "faction": "Continuum",
        "code": "CON"
      },
      {
        "id": "CON-029",
        "name": "Beyond the Fifth",
        "type": "Spell",
        "cost": 6,
        "resource": 1,
        "statsText": "-",
        "rules": "Sequence Complete - Draw 2 cards. Your next card this round costs 3 less, minimum 1.",
        "faction": "Continuum",
        "code": "CON"
      },
      {
        "id": "CON-030",
        "name": "Missed Beat",
        "type": "Trap",
        "cost": 3,
        "resource": 1,
        "statsText": "-",
        "rules": "When an enemy creature attacks, Shift your Sequence 1 step in its current direction. High Sequence (4/5) - If your Sequence is 4 or 5 after the Shift, that attacker gets -3 STR for this combat.",
        "faction": "Continuum",
        "code": "CON"
      }
    ],
    "Moondemons": [
      {
        "id": "MON-001",
        "name": "Bloodtrail Cub",
        "type": "Creature",
        "cost": 2,
        "resource": 1,
        "statsText": "2/3",
        "rules": "Bloodied - Bloodtrail Cub has +2 STR while attacking.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 2,
        "hp": 3,
        "legendary": false
      },
      {
        "id": "MON-002",
        "name": "Scar Dancer",
        "type": "Creature",
        "cost": 3,
        "resource": 2,
        "statsText": "3/4",
        "rules": "Bloodied - After Scar Dancer deals damage and its universal 2-HP restore resolves, you may deal 1 damage to Scar Dancer.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 3,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "MON-003",
        "name": "Pale Leech",
        "type": "Creature",
        "cost": 3,
        "resource": 2,
        "statsText": "2/5",
        "rules": "Bloodied - The first time each round Pale Leech restores HP from dealing damage, draw 1 card, then put 1 card from your hand on the bottom of your deck.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 2,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "MON-004",
        "name": "Redjaw Raider",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "4/5",
        "rules": "Bloodied - The first time each round Redjaw Raider deals combat damage, it gains +1 maximum HP permanently without restoring HP.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 4,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "MON-005",
        "name": "Woundrunner",
        "type": "Creature",
        "cost": 4,
        "resource": 1,
        "statsText": "4/4",
        "rules": "Bloodied - Woundrunner has +2 STR while attacking an already-damaged enemy creature.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 4,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "MON-006",
        "name": "Mercy Eater",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "2/6",
        "rules": "Bloodied - The first time each round another friendly Moondemon restores HP, Mercy Eater gains +1 STR this round and takes 1 damage.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 2,
        "hp": 6,
        "legendary": false
      },
      {
        "id": "MON-007",
        "name": "Moonclaw Duelist",
        "type": "Creature",
        "cost": 5,
        "resource": 1,
        "statsText": "4/6",
        "rules": "Bloodied - The first time each round Moonclaw Duelist survives creature combat and remains Bloodied, it may immediately make one additional attack.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 4,
        "hp": 6,
        "legendary": false
      },
      {
        "id": "MON-008",
        "name": "Veinbreaker",
        "type": "Creature",
        "cost": 5,
        "resource": 1,
        "statsText": "5/5",
        "rules": "Bloodied - Before Veinbreaker attacks, you may deal 1 damage to it. If you do, it gains +3 STR for that combat.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 5,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "MON-009",
        "name": "Hunger Matriarch",
        "type": "Creature",
        "cost": 7,
        "resource": 1,
        "statsText": "4/8",
        "rules": "Bloodied - The first time each round another Bloodied friendly Moondemon deals damage, restore 1 additional HP to that creature after its universal restore.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 4,
        "hp": 8,
        "legendary": false
      },
      {
        "id": "MON-010",
        "name": "Nightpack Alpha",
        "type": "Creature",
        "cost": 7,
        "resource": 1,
        "statsText": "5/7",
        "rules": "Bloodied - Other Bloodied friendly Moondemons have +1 STR.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 5,
        "hp": 7,
        "legendary": false
      },
      {
        "id": "MON-011",
        "name": "Eclipse Ravager",
        "type": "Creature",
        "cost": 8,
        "resource": 1,
        "statsText": "6/8",
        "rules": "Bloodied - Whenever Eclipse Ravager destroys an enemy creature in combat, deal 1 damage to every other enemy creature. Eclipse Ravager is the source of that damage.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 6,
        "hp": 8,
        "legendary": false
      },
      {
        "id": "MON-012",
        "name": "Moonfang Sovereign",
        "type": "Creature",
        "cost": 9,
        "resource": 1,
        "statsText": "7/9",
        "rules": "Bloodied - Moonfang Sovereign deals +3 damage on direct attacks. After it attacks, deal 1 damage to it.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 7,
        "hp": 9,
        "legendary": false
      },
      {
        "id": "MON-013",
        "name": "Ward Sigil",
        "type": "Sigil",
        "cost": 3,
        "resource": 2,
        "statsText": "Face-down ally attachment",
        "rules": "SIGIL — Attach face-down to a friendly Moondemon. When that ally would receive damage, reveal: prevent all of that damage, then give it Shield equal to the prevented damage.",
        "faction": "Moondemons",
        "code": "MON",
        "sigilEffect": "ward"
      },
      {
        "id": "MON-014",
        "name": "Bloodwake Sigil",
        "type": "Sigil",
        "cost": 3,
        "resource": 2,
        "statsText": "Face-down ally attachment",
        "rules": "SIGIL — Attach face-down to a friendly Moondemon. When that ally becomes Bloodied, reveal: it gains +3 STR this round and Shield 2.",
        "faction": "Moondemons",
        "code": "MON",
        "sigilEffect": "bloodwake"
      },
      {
        "id": "MON-015",
        "name": "Fang Sigil",
        "type": "Sigil",
        "cost": 3,
        "resource": 2,
        "statsText": "Face-down ally attachment",
        "rules": "SIGIL — Attach face-down to a friendly Moondemon. When that ally attacks while Bloodied, reveal: it gains +3 STR for that combat.",
        "faction": "Moondemons",
        "code": "MON",
        "sigilEffect": "fang"
      },
      {
        "id": "MON-016",
        "name": "Reprisal Sigil",
        "type": "Sigil",
        "cost": 3,
        "resource": 2,
        "statsText": "Face-down ally attachment",
        "rules": "SIGIL — Attach face-down to a friendly Moondemon. When that ally survives combat damage from an enemy creature, reveal: deal 2 damage to that enemy after combat.",
        "faction": "Moondemons",
        "code": "MON",
        "sigilEffect": "reprisal"
      },
      {
        "id": "MON-017",
        "name": "Redline Sigil",
        "type": "Sigil",
        "cost": 3,
        "resource": 2,
        "statsText": "Face-down ally attachment",
        "rules": "SIGIL — Attach face-down to a friendly Moondemon. When that ally would heal to full after having been Bloodied, reveal: leave it at 1 HP below maximum instead and it permanently gains +1 STR / +1 maximum HP.",
        "faction": "Moondemons",
        "code": "MON",
        "sigilEffect": "redline"
      },
      {
        "id": "MON-018",
        "name": "Feast Sigil",
        "type": "Sigil",
        "cost": 3,
        "resource": 1,
        "statsText": "Face-down ally attachment",
        "rules": "SIGIL — Attach face-down to a friendly Moondemon. When that ally destroys an enemy creature in combat, reveal: restore 3 HP to it, then draw 1 card and put 1 card from your hand on the bottom of your deck.",
        "faction": "Moondemons",
        "code": "MON",
        "sigilEffect": "feast"
      },
      {
        "id": "MON-019",
        "name": "Blood in the Water",
        "type": "Trap",
        "cost": 3,
        "resource": 1,
        "statsText": "-",
        "rules": "After an enemy creature takes damage and survives, Bloodied - Choose a Bloodied friendly Moondemon. Its next attack this round gains +2 STR for that combat.",
        "faction": "Moondemons",
        "code": "MON"
      },
      {
        "id": "MON-020",
        "name": "Last Bite",
        "type": "Trap",
        "cost": 3,
        "resource": 1,
        "statsText": "-",
        "rules": "When a Bloodied friendly Moondemon is destroyed by an enemy creature, deal 2 damage to that enemy. Bloodied - Another Bloodied friendly Moondemon gains +2 maximum HP permanently without restoring HP.",
        "faction": "Moondemons",
        "code": "MON"
      },
      {
        "id": "MON-021",
        "name": "Goremane Pup",
        "type": "Creature",
        "cost": 2,
        "resource": 2,
        "statsText": "2/3",
        "rules": "Bloodied - The first time each round Goremane Pup takes damage, it gains +1 STR this round.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 2,
        "hp": 3,
        "legendary": false
      },
      {
        "id": "MON-022",
        "name": "Crimson Surgeon",
        "type": "Creature",
        "cost": 3,
        "resource": 2,
        "statsText": "2/5",
        "rules": "Bloodied - Once per round, deal 1 damage to another friendly Moondemon. That creature gains +1 maximum HP permanently without restoring HP and +1 STR this round.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 2,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "MON-023",
        "name": "Dusk Butcher",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "4/5",
        "rules": "Bloodied - When Dusk Butcher attacks a damaged enemy creature, it gains +2 STR for that combat.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 4,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "MON-024",
        "name": "Ravine Stalker",
        "type": "Creature",
        "cost": 5,
        "resource": 1,
        "statsText": "5/5",
        "rules": "Bloodied - When Ravine Stalker attacks a damaged enemy creature, it does not take retaliation damage from that combat.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 5,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "MON-025",
        "name": "Pale Moon Tyrant",
        "type": "Creature",
        "cost": 7,
        "resource": 1,
        "statsText": "6/8",
        "rules": "Bloodied - The first time each round another friendly Moondemon becomes Bloodied, that creature gains +2 STR this round.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 6,
        "hp": 8,
        "legendary": false
      },
      {
        "id": "MON-026",
        "name": "Vespera, Redfang Matriarch",
        "type": "Legendary Creature",
        "cost": 9,
        "resource": 2,
        "statsText": "8/11",
        "rules": "Bloodied - The first time each round Vespera deals damage, you may redirect up to 2 HP of her universal restore to another friendly Moondemon. BLOODTHIRST - The Pack Drinks Together: the first Moondemon destroyed by Bloodthirst each round gives +3 STR / +3 maximum and current HP to every other friendly Moondemon instead of +2/+2. FRENZIED - Redline: the first time each round a Bloodied friendly Moondemon would return to full HP and be destroyed by Frenzied, deal 1 damage to it before the full-HP death check.",
        "faction": "Moondemons",
        "code": "MON",
        "str": 8,
        "hp": 11,
        "legendary": true
      },
      {
        "id": "MON-027",
        "name": "Blood Price",
        "type": "Spell",
        "cost": 3,
        "resource": 2,
        "statsText": "-",
        "rules": "Lose 2 Health. Gain 3 resources this round. Bloodied - If you control a Bloodied Moondemon, one Bloodied friendly Moondemon gains +2 STR this round.",
        "faction": "Moondemons",
        "code": "MON"
      },
      {
        "id": "MON-028",
        "name": "Pack Feeding",
        "type": "Spell",
        "cost": 4,
        "resource": 2,
        "statsText": "-",
        "rules": "Restore 2 HP to up to three friendly Moondemons. Bloodied - For each Bloodied target, you may replace 1 of that healing with +1 maximum HP permanently without restoring that point.",
        "faction": "Moondemons",
        "code": "MON"
      },
      {
        "id": "MON-029",
        "name": "Moonrage",
        "type": "Spell",
        "cost": 6,
        "resource": 1,
        "statsText": "-",
        "rules": "Bloodied - All Bloodied friendly Moondemons gain +2 STR this round. After each of those creatures takes a combat action, deal 1 damage to it.",
        "faction": "Moondemons",
        "code": "MON"
      },
      {
        "id": "MON-030",
        "name": "Predator's Reprisal",
        "type": "Trap",
        "cost": 4,
        "resource": 1,
        "statsText": "-",
        "rules": "When an enemy creature destroys one of your creatures, Bloodied - Choose another Bloodied friendly Moondemon. If it has not acted this round, it may immediately attack that enemy. After the attack, deal 1 damage to it.",
        "faction": "Moondemons",
        "code": "MON"
      }
    ],
    "Eliteborn": [
      {
        "id": "ELI-001",
        "name": "Page of the Line",
        "type": "Creature",
        "cost": 2,
        "resource": 1,
        "statsText": "1/3",
        "rules": "Formation (1) - Page of the Line has +2 STR.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 1,
        "hp": 3,
        "legendary": false
      },
      {
        "id": "ELI-002",
        "name": "Banner Squire",
        "type": "Creature",
        "cost": 3,
        "resource": 2,
        "statsText": "1/4",
        "rules": "Formation (2) - The other creature in this Formation has +0 STR / +1 maximum and current HP.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 1,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "ELI-003",
        "name": "Twinblade Cadet",
        "type": "Creature",
        "cost": 3,
        "resource": 2,
        "statsText": "2/3",
        "rules": "Formation (2) - Twinblade Cadet has +2 STR / +1 maximum and current HP.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 2,
        "hp": 3,
        "legendary": false
      },
      {
        "id": "ELI-004",
        "name": "Oathguard",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "3/5",
        "rules": "Formation (3) - Oathguard has Taunt and +1 STR.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 3,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "ELI-005",
        "name": "Bastion Captain",
        "type": "Creature",
        "cost": 4,
        "resource": 1,
        "statsText": "2/6",
        "rules": "Formation (4) - The first damage dealt to a creature in this Formation each round is reduced by 2 before any Disperse split.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 2,
        "hp": 6,
        "legendary": false
      },
      {
        "id": "ELI-006",
        "name": "Formation Adept",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "3/4",
        "rules": "Formation (3) - Formation Adept has +1 STR / +1 maximum and current HP. The first time its Formation becomes exactly 3, draw 1 card, then put 1 card from your hand on the bottom of your deck.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 3,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "ELI-007",
        "name": "Relay Knight",
        "type": "Creature",
        "cost": 5,
        "resource": 1,
        "statsText": "4/5",
        "rules": "Formation (2) - The first time each round an Equip attached to a creature in this Formation grants a stat bonus or triggered effect, the other creature gains +1 STR this round.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 4,
        "hp": 5,
        "legendary": false
      },
      {
        "id": "ELI-008",
        "name": "Bondwarden",
        "type": "Creature",
        "cost": 5,
        "resource": 1,
        "statsText": "3/7",
        "rules": "Formation (4) - At the start of your round, restore 2 HP divided among creatures in this Formation.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 3,
        "hp": 7,
        "legendary": false
      },
      {
        "id": "ELI-009",
        "name": "Standard Marshal",
        "type": "Creature",
        "cost": 7,
        "resource": 1,
        "statsText": "4/7",
        "rules": "Formation (5) - Other creatures in this Formation have +1 STR.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 4,
        "hp": 7,
        "legendary": false
      },
      {
        "id": "ELI-010",
        "name": "Crowned Intercessor",
        "type": "Creature",
        "cost": 7,
        "resource": 1,
        "statsText": "4/8",
        "rules": "Formation (3) - Once per round, when another creature in this Formation is targeted by an attack, Crowned Intercessor may become the target instead.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 4,
        "hp": 8,
        "legendary": false
      },
      {
        "id": "ELI-011",
        "name": "United Colossus",
        "type": "Creature",
        "cost": 8,
        "resource": 1,
        "statsText": "5/9",
        "rules": "Formation (5+) - United Colossus has +1 STR for each other creature in this Formation, maximum +4 STR.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 5,
        "hp": 9,
        "legendary": false
      },
      {
        "id": "ELI-012",
        "name": "First Among Equals",
        "type": "Creature",
        "cost": 9,
        "resource": 1,
        "statsText": "6/9",
        "rules": "Formation (1) - First Among Equals has +3 STR / +3 maximum and current HP. Formation (4) - Other creatures in this Formation have +1 STR / +1 maximum and current HP.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 6,
        "hp": 9,
        "legendary": false
      },
      {
        "id": "ELI-013",
        "name": "Tighten Ranks",
        "type": "Spell",
        "cost": 2,
        "resource": 2,
        "statsText": "-",
        "rules": "Choose one Formation. Until end of round, its printed Formation effects may treat its size as exactly 1 higher or 1 lower. This does not count as a card joining and cannot activate Disperse or a Rise as One growth trigger.",
        "faction": "Eliteborn",
        "code": "ELI"
      },
      {
        "id": "ELI-014",
        "name": "Coordinated Strike",
        "type": "Spell",
        "cost": 3,
        "resource": 2,
        "statsText": "-",
        "rules": "Choose two creatures in the same Formation. If both attack the same enemy this round, the second attacker gains +3 STR for that combat.",
        "faction": "Eliteborn",
        "code": "ELI"
      },
      {
        "id": "ELI-015",
        "name": "Rotate the Line",
        "type": "Spell",
        "cost": 3,
        "resource": 2,
        "statsText": "-",
        "rules": "Choose two creatures in the same Formation. Move up to 2 damage from one onto the other. This cannot reduce the receiving creature below 1 HP.",
        "faction": "Eliteborn",
        "code": "ELI"
      },
      {
        "id": "ELI-016",
        "name": "Rally Standard",
        "type": "Spell",
        "cost": 5,
        "resource": 1,
        "statsText": "-",
        "rules": "Choose a Formation. Its creatures gain +1 STR this round; if its Formation size is 4 or greater, they gain +2 STR instead.",
        "faction": "Eliteborn",
        "code": "ELI"
      },
      {
        "id": "ELI-017",
        "name": "Reinforce",
        "type": "Spell",
        "cost": 5,
        "resource": 1,
        "statsText": "-",
        "rules": "Summon two 1 STR / 1 HP Recruit creatures into open creature slots. Choose a Formation for each Recruit as it enters, or place it alone as Formation (1).",
        "faction": "Eliteborn",
        "code": "ELI"
      },
      {
        "id": "ELI-018",
        "name": "Shared Purpose",
        "type": "Spell",
        "cost": 5,
        "resource": 1,
        "statsText": "-",
        "rules": "Choose a Formation. Until end of round, the first time one creature in it gains STR or HP from another friendly card effect, every other creature in that Formation gains +1 to the same stat this round.",
        "faction": "Eliteborn",
        "code": "ELI"
      },
      {
        "id": "ELI-019",
        "name": "Tower Shield",
        "type": "Equip",
        "cost": 3,
        "resource": 2,
        "statsText": "+0 STR / +2 HP",
        "rules": "Attach to a friendly Creature with no Equip. This Equip counts as 1 card in that creature's Formation. Formation (2) - Attached creature has Taunt.",
        "faction": "Eliteborn",
        "code": "ELI",
        "equipStr": 0,
        "equipHp": 2
      },
      {
        "id": "ELI-020",
        "name": "Oathblade",
        "type": "Equip",
        "cost": 3,
        "resource": 2,
        "statsText": "+2 STR / +0 HP",
        "rules": "Attach to a friendly Creature with no Equip. This Equip counts as 1 card in that creature's Formation. Formation (3) - Attached creature gains +2 STR for its first combat each round.",
        "faction": "Eliteborn",
        "code": "ELI",
        "equipStr": 2,
        "equipHp": 0
      },
      {
        "id": "ELI-021",
        "name": "Shieldmate Recruit",
        "type": "Creature",
        "cost": 2,
        "resource": 2,
        "statsText": "1/4",
        "rules": "Formation (2) - The first combat damage dealt each round to the other creature in this Formation is reduced by 1.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 1,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "ELI-022",
        "name": "Line Medic",
        "type": "Creature",
        "cost": 3,
        "resource": 2,
        "statsText": "2/4",
        "rules": "Formation (3) - At the start of your round, restore 2 HP to a creature in this Formation.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 2,
        "hp": 4,
        "legendary": false
      },
      {
        "id": "ELI-023",
        "name": "Paired Lancer",
        "type": "Creature",
        "cost": 4,
        "resource": 2,
        "statsText": "4/3",
        "rules": "Formation (2) - Paired Lancer has +2 STR / +2 maximum and current HP.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 4,
        "hp": 3,
        "legendary": false
      },
      {
        "id": "ELI-024",
        "name": "Formation Engineer",
        "type": "Creature",
        "cost": 5,
        "resource": 1,
        "statsText": "3/6",
        "rules": "Formation (4) - The first Equip you attach each round to a creature in this Formation costs 1 less, minimum 1.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 3,
        "hp": 6,
        "legendary": false
      },
      {
        "id": "ELI-025",
        "name": "House Champion",
        "type": "Creature",
        "cost": 7,
        "resource": 1,
        "statsText": "6/7",
        "rules": "Formation (3) - Once per round, when another creature in this Formation would be destroyed by combat damage, deal 2 damage to House Champion. If House Champion survives, prevent 2 of that damage to the other creature.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 6,
        "hp": 7,
        "legendary": false
      },
      {
        "id": "ELI-026",
        "name": "High Marshal Caedryn",
        "type": "Legendary Creature",
        "cost": 9,
        "resource": 2,
        "statsText": "7/11",
        "rules": "Formation (5+) — The first time each round an Equip joins Caedryn's Formation, draw 1 card, then put 1 card from your hand on the bottom of your deck. WE STAND TOGETHER — No Empty Place: Caedryn's Formation gains Disperse at Formation 4+ instead of 5+, and the first time each round damage is dispersed there, reduce total damage by 2 before splitting it. RISE AS ONE. DIE AS ONE. — One Oath: the first time each round a card joins any Formation at size 2 or higher, the Rise growth for that addition is +2 STR / +2 maximum and current HP instead of +1/+1.",
        "faction": "Eliteborn",
        "code": "ELI",
        "str": 7,
        "hp": 11,
        "legendary": true
      },
      {
        "id": "ELI-027",
        "name": "Drill Standard",
        "type": "Equip",
        "cost": 3,
        "resource": 2,
        "statsText": "+1 STR / +1 HP",
        "rules": "Attach to a friendly Creature with no Equip. This Equip counts as 1 card in that creature's Formation. Formation (4) - When Drill Standard joins this Formation, all creatures in it gain +1 STR this round.",
        "faction": "Eliteborn",
        "code": "ELI",
        "equipStr": 1,
        "equipHp": 1
      },
      {
        "id": "ELI-028",
        "name": "Muster Horn",
        "type": "Equip",
        "cost": 4,
        "resource": 2,
        "statsText": "+0 STR / +1 HP",
        "rules": "Attach to a friendly Creature with no Equip. This Equip counts as 1 card in that creature's Formation. Formation (3) - At the start of your round, if you have an open creature slot, summon a 1 STR / 1 HP Recruit into this Formation. This normally changes the Formation to size 4.",
        "faction": "Eliteborn",
        "code": "ELI",
        "equipStr": 0,
        "equipHp": 1
      },
      {
        "id": "ELI-029",
        "name": "Banner of Seven",
        "type": "Equip",
        "cost": 6,
        "resource": 1,
        "statsText": "+1 STR / +2 HP",
        "rules": "Attach to a friendly Creature with no Equip. This Equip counts as 1 card in that creature's Formation. Formation (5+) - Creatures in this Formation have +0 STR / +1 maximum and current HP.",
        "faction": "Eliteborn",
        "code": "ELI",
        "equipStr": 1,
        "equipHp": 2
      },
      {
        "id": "ELI-030",
        "name": "Take My Place",
        "type": "Equip",
        "cost": 4,
        "resource": 1,
        "statsText": "+1 STR / +2 HP",
        "rules": "Attach to a friendly Creature with no Equip. This Equip counts as 1 card in that creature's Formation. Formation (2) - Once per round, when the other creature in this Formation is targeted by an attack, the attached creature may become the target instead.",
        "faction": "Eliteborn",
        "code": "ELI",
        "equipStr": 1,
        "equipHp": 2
      }
    ]
  }
};
